### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by lisun-ai** [batmanlab/HA-GAN#5]
- [X] Convert paper to TMI style
- [X] Fix mode collapse on ADNI data set
- [X] GPU memory comsuption measurement
- [X] PCA for evaluation
- [ ] More evaluation schemes
- [ ] Explore latent space
- [ ] Draw network archtecture
